obj-m :=brMtuMod.o
brMtuMod-objs := mtu_mod_module.o mtu_mod_proc.o mtu_mod_br.o

KDIR :=/lib/modules/$(shell uname -r)/build

PWD := $(shell pwd)

default:
	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
	
clean:
	rm -f *.o *.ko *.order *.symvers