#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#Makefile for hotspotfd code
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

CFLAGS += $(addprefix -I,$(INCPATH))
CFLAGS += -fno-exceptions 
CFLAGS += -Os 
CFLAGS += -Wall -Wextra
ifndef NO_TRIGGER
CFLAGS += -DCONFIG_BUILD_TRIGGER
endif

LDFLAGS += -lutils_gw
LDFLAGS += -lsyscfg
LDFLAGS += -lsysevent
LDFLAGS += -lulog
LDFLAGS += -lpthread
# The following libraries are required for nfq_handler.
#LDFLAGS += -lnetfilter_queue -lnfnetlink -lssl

targets_hotspotfd := hotspotfd
targets_hotspotfd := $(addprefix $(ComponentBuildDir)/,$(targets_hotspotfd))

source_files_hotspotfd := hotspotfd.c
obj_files_hotspotfd := $(addprefix $(ComponentBuildDir)/,$(source_files_hotspotfd:%.c=%.o))

$(targets_hotspotfd): $(obj_files_hotspotfd)

all: $(targets_hotspotfd) install

clean: 
	rm -f $(ComponentBuildDir)

install:
	@echo "Copying...[$(targets_hotspotfd) to SBIN directory]"
	@install -d -m 0755 $(CCSP_INSTALL_ROOT)/usr/sbin
	@install -m 0755 $(targets_hotspotfd) $(CCSP_INSTALL_ROOT)/usr/sbin/

.PHONY : all clean install

#
# include custom post makefile, if exists
#
ifneq ($(findstring $(CCSP_CMPNT_BUILD_CUSTOM_MK_POST), $(wildcard $(ComponentBoardDir)/*.mk)), )
    include $(ComponentBoardDir)/$(CCSP_CMPNT_BUILD_CUSTOM_MK_POST)
endif

