#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#Makefile for arp_solicitation code
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

CFLAGS += $(addprefix -I,$(INCPATH))
CFLAGS += -fno-exceptions 
CFLAGS += -Os 
CFLAGS += -Wall -Wextra
ifndef NO_TRIGGER
CFLAGS += -DCONFIG_BUILD_TRIGGER
endif

LDFLAGS += -L./ -lnfnetlink
LDFLAGS += -L./ -lnetfilter_queue
# The following libraries are required for nfq_handler.
#LDFLAGS += -lnetfilter_queue -lnfnetlink -lssl

targets_arpd := hotspot_arpd
targets_arpd := $(addprefix $(ComponentBuildDir)/,$(targets_arpd))

source_files_arpd := hotspot_arpd.c
obj_files_arpd := $(addprefix $(ComponentBuildDir)/,$(source_files_arpd:%.c=%.o))

$(targets_arpd): $(obj_files_arpd)

all: build_pre $(targets_arpd) install

build_pre:
	rm -f libnetfilter_queue.so
	ln -s $(SDK_PATH)/build/vgwsdk/fs/gw/lib/libnetfilter_queue.so.1 libnetfilter_queue.so
	rm -f libnfnetlink.so.0
	ln -s $(SDK_PATH)/build/vgwsdk/fs/gw/lib/libnfnetlink.so.0 libnfnetlink.so.0

clean: 
	rm -f $(ComponentBuildDir)

install:
	@echo "Copying...[$(targets_arpd) to SBIN directory]"
	@install -d -m 0755 $(CCSP_INSTALL_ROOT)/usr/sbin
	@install -m 0755 $(targets_arpd) $(CCSP_INSTALL_ROOT)/usr/sbin/

.PHONY : all clean install

#
# include custom post makefile, if exists
#
ifneq ($(findstring $(CCSP_CMPNT_BUILD_CUSTOM_MK_POST), $(wildcard $(ComponentBoardDir)/*.mk)), )
    include $(ComponentBoardDir)/$(CCSP_CMPNT_BUILD_CUSTOM_MK_POST)
endif

