#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

obj-m :=brMtuMod.o
brMtuMod-objs := mtu_mod_module.o mtu_mod_proc.o mtu_mod_br.o

#KDIR :=/lib/modules/$(shell uname -r)/build

PWD := $(shell pwd)
KDIR :=$(SDK_PATH)/kernel/ti/linux-2.6.39.3/src

export INSTALL_MOD_DIR := /drivers/net
export INSTALL_MOD_PATH=$(CCSP_ROOT_DIR)/Out/$(CcspArch)-$(CcspBoard)

#CFLAGS =-D__KERNEL__

build:  build_rule
config: config_rule
install:    install_rule
uninstall:  uninstall_rule

all:    config build install

config_rule:

build_rule:
	$(MAKE) ARCH=arm CROSS_COMPILE=armeb-unknown-linux-uclibcgnueabi- -C $(KDIR) SUBDIRS=$(PWD) modules
	
clean_rule:
	rm -f *.o *.ko *.order *.symvers

install_rule:
	$(MAKE) ARCH=arm CROSS_COMPILE=armeb-unknown-linux-uclibcgnueabi- -C $(KDIR) SUBDIRS=$(PWD) modules_install
    
uninstall_rule:
	@find $(TI_filesystem_path)/lib/modules/ -name brMtuMod.ko | xargs rm -rf
    
